clone_folder: "c:\\zephyr"
environment:
  APPVEYOR_SSH_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAs17FMCcqFt4GWaZdXilewWPveDFiS6NXuV5OKyosf6VkJLwu0mghEvxnMBdK4PyeUgalZzPRy8hb9JoGPkiD3SqZ0bOSUSY2NgUdUdbCDzuHdM3Ga/nSs2G/IvpY0c8Cyh1MCdYel4N2kQ3qWYkmBsfEScPXTV4DI/WhaSJzJBdhoz1NfNAZY+p6kmQ+6YIt2yziXFWT6p/JL0er+5KNd60ZE67n3crZ+X2fHNW/eUwL+VNUlSaejwRNAu0wgyvIiC+pdnET9NpvwcPooDU/FM5SkEWD4j1ivBUa0deCa0F5hmpEuok0oa2mac9+BN6gK3GmQ4fDKzrmpz2qsFQ0Cw=="
cache:
  - c:\zephyr\dist-newstyle
  - c:\Users\appveyor\AppData\Roaming\cabal\packages
  - c:\Users\appveyor\AppData\Roaming\cabal\store
init:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
install:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - set PATH=%AppData%\npm;%PATH%
  - choco install ghc --version 8.6.5
  - choco install cabal
  - choco install purescript --version 0.13.6
  - choco install nodejs
  - choco install bower
  - refreshenv
  - ghc --version
  - cabal --version
  - cabal update -v
build_script:
  - ps: |
      # TODO: enable -Werror
      cabal build exe:zephyr
      cabal build -f test-with-cabal zephyr-test
  - ps: bash bundle/build.sh win64
test_script:
  # TODO: not testing `-m TestLib`
  - cabal run -f test-with-cabal zephyr-test -- -m generators -m dceEval -m dceExpr
artifacts:
  - path: bundle\x86_64-windows.tar.gz
    name: x86_64-windows.tar.gz
  - path: bundle\x86_64-windows.sha
    name: x86_64-windows.sha
deploy:
  - provider: GitHub
    auth_token:
      secure: x7NfETL6i3LCuKpv9WZf4k/RmnZTr5glvheuBbl7FvFhtqDhc4YynBufhbjYKgLC
    artifact: x86-64-windows.tar.gz,x86-64-windows.sha
    draft: true
    force_update: true
    on:
      appveyor_repo_tag: true
on_finish:
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\build-reports.log || true
  # remove files that are regenerated by 'cabal update'
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\00-index.* || true
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\*.json || true
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\01-index.cache || true
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\01-index.tar || true
  - rm -fv  c:\Users\appveyor\AppData\Roaming\cabal\packages\hackage.haskell.org\01-index.tar.idx || true
  - rm -rfv c:\Users\appveyor\AppData\Roaming\cabal\packages\head.hackage || true
