clone_folder: "c:\\zephyr"
cache:
  - c:\zephyr\dist-newstyle
install:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - set PATH=%AppData%\npm;%PATH%
  - choco install ghc --version 8.6.5
  - choco install cabal
  - choco install purescript --version 0.13.6
  - choco install nodejs
  - choco install bower
  - refreshenv
  - ghc --version
  - cabal --version
  - cabal update -v
build_script:
  - ps: |
      # TODO: enable -Werror
      cabal build exe:zephyr
      cabal build -f test-with-cabal zephyr-test
  - ps: bash bundle/build.sh win64
test_script:
  # TODO: not testing `-m TestLib`
  - cabal run -f test-with-cabal zephyr-test -- -m generators -m dceEval -m dceExpr
artifacts:
  - path: bundle\x86_64-windows.tar.gz
    name: x86_64-windows.tar.gz
  - path: bundle\x86_64-windows.sha
    name: x86_64-windows.sha
deploy:
  - provider: GitHub
    auth_token:
      secure: gHIxz3scq98LOgduo20IiKNFcLOmcKHHKH0qI4/z4TawrmbR+MV/rb1mG9GCXf7M
    artifact: x86-64-windows.tar.gz,x86-64-windows.sha
    draft: true
    force_update: true
    on:
      appveyor_repo_tag: true
