flags: {}
extra-package-dbs: []
nix:
  enable: false
  shell-file: shell.nix
packages:
- .
extra-deps:
- git: https://github.com/purescript/purescript
  commit: "44397e5107dad601a52e0888a24993bec33e8fc0"
- git: https://github.com/phadej/spdx
  commit: "4288df6e4b7840eb94d825dcd446b42fef25ef56"
- network-3.0.1.1
- aeson-1.3.1.1
- language-javascript-0.6.0.13
resolver: lts-13.20
