flags: {}
extra-package-dbs: []
nix:
  enable: false
  shell-file: shell.nix
packages:
- .
extra-deps:
- QuickCheck-2.12.1
- hspec-2.5.6
- hspec-core-2.5.6
- hspec-discover-2.5.6
- aeson-1.3.1.1
- git: https://github.com/purescript/purescript
  commit: "a8e0911222f46411776978a13866eb097175162c"
- git: https://github.com/phadej/spdx
  commit: "4288df6e4b7840eb94d825dcd446b42fef25ef56"
resolver: lts-12.0
