flags: {}
extra-package-dbs: []
nix:
  enable: true
  shell-file: shell.nix
packages:
- .
extra-deps:
- pipes-http-1.0.5
- purescript-0.12.0
- QuickCheck-2.12.1
- hspec-2.5.6
- hspec-core-2.5.6
- hspec-discover-2.5.6
resolver: lts-10.3
