flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: git@github.com:coot/purescript.git
    commit: a99284b4b2e91b8372b07a3705b61e6461e06dfa
  extra-dep: true
extra-deps:
- pipes-http-1.0.5
resolver: nightly-2017-09-10
