flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: git@github.com:purescript/purescript.git
    commit: a5aad4a0d08d53a468454b1f4a2ef0bd04d6cd24
  extra-dep: true
extra-deps:
- pipes-http-1.0.5
resolver: nightly-2017-09-10
