flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/coot/purescript.git
    commit: cbda52a93362fd902340b2663f6823d3a7d46c93
  extra-dep: true
extra-deps:
- pipes-http-1.0.5
resolver: lts-10.3
