flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: git@github.com:coot/purescript.git
    commit: 29ef583ae754ca963dc245e8a1b63445f1eeb90e
  extra-dep: true
extra-deps:
- listsafe-0.1.0.1
- pipes-http-1.0.5
resolver: lts-8.5
