flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/coot/purescript.git
    commit: 459d9aa4f0dea548938fab2790e9dbeaabf91d0e
  extra-dep: true
extra-deps:
- pipes-http-1.0.5
resolver: lts-10.3
