flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/purescript/purescript.git
    commit: 939f4bd2f145e243e57b267b439085aae87983f2
  extra-dep: true
extra-deps:
- pipes-http-1.0.5
resolver: lts-10.3
