name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.2'
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup paths
      run: echo "::add-path::${HOME}/.cabal/bin"
    - name: Install dependencies
      run: |
        cabal update
        cabal install purescript-0.13.8
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build exe:zephyr
    - name: Run tests
      run: cabal run zephyr-test -- -m generators -m dceEval -m dceExpr -m TestLib
