name: zephyr

on: [push]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.2'
    - name: Setup cabal paths
      run: |
        echo "::add-path::${HOME}/AppData/Roaming/cabal/bin"
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install bower
      run: npm install --global bower
    - name: Check versions
      run: |
        node --version
        npm --version
        bower --version
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Update cabal
      run: cabal update
    - uses: actions/checkout@v2
    - name: Install zephyr's dependencies
      run: |
        cabal install --install-method=copy --overwrite-policy=always purescript-0.13.8
        cabal build --only-dependencies
    - name: Build zephyr
      run: |
        cp cabal.project.ci cabal.project.local
        cabal build exe:zephyr
    - name: Run tests
      # We dont' run `-m TestLib` as on posix; Getting bower path on Windows
      # recognised by `readProcessWithExitCode` is impossible.
      run: cabal run zephyr-test -- -m generators -m dceEval -m dceExpr
